generation_sizes:
  !tup [4, 4]: 'it'
  !tup [4, 8]: 'it'
  !tup [8, 4]: 'it'
  !tup [8, 8]: 'it'
  !tup [14, 8]: 'it'
  !tup [8, 14]: 'it'
  !tup [14, 14]: 'it'
  !tup [20, 14]: 'oot'
  !tup [20, 20]: 'oot'
controlled_conditions:
- control_name: "walls"
  condition: "wall-ratio"
  mapping: "value/(size[0] * size[1])"
  amount_per_pin: 100
  values:
    !tup [4, 4]: !range [0, 15]
    !tup [4, 8]: !range [0, 31]
    !tup [8, 4]: !range [0, 31]
    !tup [8, 8]: !range [0, 63]
    !tup [14,8]: !range [0, 99]
    !tup [8,14]: !range [0, 99]
    !tup [14,14]: !range [0, 99]
    !tup [20,14]: !range [0, 99]
    !tup [20,20]: !range [0, 99]
- control_name: "maximum-path-length"
  condition: "maximum-path-length-norm"
  mapping: "value/(size[0] * size[1])"
  amount_per_pin: 100
  values:
    !tup [4, 4]: !range [0, 8]
    !tup [4, 8]: !range [0, 16]
    !tup [8, 4]: !range [0, 16]
    !tup [8, 8]: !range [0, 32]
    !tup [14,8]: !range [0, 61]
    !tup [8,14]: !range [0, 61]
    !tup [14,14]: !range [0, 98]
    !tup [20,14]: !range [0, 99]
    !tup [20,20]: !range [0, 99]
trials: 1