name: msgen
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>=3.9
  - numpy>=1.20
  - scikit-learn>=0.24
  - PyYAML>=6.0
  - Pillow>=9.2.0
  - tqdm>=4.62
  - pytorch>=1.11
  - cudatoolkit>=11.3
  - matplotlib>=3.4
  - seaborn>=0.11
  - pip
  - pip:
    - git+https://github.com/yahiaetman/sokosolve