!obj:methods.ms_gflownet.trainer/Trainer.Config
game_config: !inc "~/../game.yml"

conditions:
  - "pushed-crate-ratio"
  - "difficulty"

sizes:
  - !tup [3, 3]
  - !tup [4, 4]
  - !tup [5, 5]
  - !tup [3, 5]
  - !tup [5, 3]

dataset_config: !obj:methods.ms_gflownet.dataset/Dataset.Config
  data_augmentation: true
  diversity_sampling: true
  diversity_reward: true
  property_reward: "math.log(item['solution-length'])"
  cluster_key: &key "(item['pushed-crates'], item['solution-length']//(sum(size)//2))"
  cluster_threshold:
    !tup [3, 3]: 1
    !tup [4, 4]: 1
    !tup [5, 5]: 1
    !tup [3, 5]: 1
    !tup [5, 3]: 1

condition_model_config: !obj:methods.ms_conditions/KDEConditionModel.Config
  noise_factors:
    pushed-crate-ratio: !tup [-2, 4]
    difficulty: !tup [-10, 20]
  diversity_sampling: true
  cluster_key: *key
  cluster_threshold:
    !tup [3, 3]: 1
    !tup [4, 4]: 1
    !tup [5, 5]: 1
    !tup [3, 5]: 1
    !tup [5, 3]: 1

generator_config: !inc "configs/models/snake_ms_ce_gru.yml"

optimizer_config: !obj:methods.ms_gflownet.optimizers/GFlowMSTBOptimizer.Config {}

training_steps: 10000
batch_size: 32
checkpoint_period: 1000

heatmap_config: !inc "~/..//heatmap.yml"
heatmap_render_period: 100