!obj:methods.ms_gflownet.trainer/Trainer.Config
game_config: !inc "~/../game.yml"

conditions:
  - "wall-ratio"
  - "maximum-path-length-norm"

sizes:
  - !tup [4, 4]
  - !tup [4, 8]
  - !tup [8, 4]
  - !tup [8, 8]
  - !tup [8, 14]
  - !tup [14, 8]
  - !tup [14, 14]

dataset_config: !obj:methods.ms_gflownet.dataset/Dataset.Config
  data_augmentation: false
  diversity_sampling: true
  diversity_reward: true
  property_reward: "math.log(1+item['maximum-path-length'])"
  cluster_key: "(item['walls']//10, item['maximum-path-length']//5)"
  cluster_threshold:
    !tup [4, 4]: 2
    !tup [4, 8]: 2
    !tup [8, 4]: 2
    !tup [8, 8]: 2
    !tup [8,14]: 2
    !tup [14,8]: 2
    !tup [14,14]: 2

condition_model_config: !obj:methods.ms_conditions/KDEConditionModel.Config
  noise_factors:
    wall-ratio: !tup [-2, 2]
    maximum-path-length-norm: !tup [-5, 10]
  diversity_sampling: true
  cluster_key: "(item['walls']//10, item['maximum-path-length']//5)"
  cluster_threshold:
    !tup [4, 4]: 2
    !tup [4, 8]: 2
    !tup [8, 4]: 2
    !tup [8, 8]: 2
    !tup [8,14]: 2
    !tup [14,8]: 2
    !tup [14,14]: 2

generator_config: !inc "configs/models/snake_ms_ce_gru.yml"

optimizer_config: !obj:methods.ms_gflownet.optimizers/GFlowMSTBOptimizer.Config {}

training_steps: 10000
batch_size: 32
checkpoint_period: 1000

heatmap_config: !inc "~/..//heatmap.yml"
heatmap_render_period: 100