!obj:common.heatmap/Heatmaps.Config
labels: ["Nearest Enemy Distance", "Path Length"]
coordinates: ["item['nearest-enemy-distance']", "item['path-length']"]
bounds:
  !tup [3, 4]: !tup [!tup [1, 12], !tup [1, 24]]
  !tup [3, 6]: !tup [!tup [1, 18], !tup [1, 36]]
  !tup [5, 4]: !tup [!tup [1, 20], !tup [1, 40]]
  !tup [5, 6]: !tup [!tup [1, 30], !tup [1, 60]]
  !tup [5,11]: !tup [!tup [1, 55], !tup [1,110]]
  !tup [7, 6]: !tup [!tup [1, 42], !tup [1, 84]]
  !tup [7,11]: !tup [!tup [1, 77], !tup [1,154]]