!obj:methods.ms_gflownet.trainer/Trainer.Config
game_config: !inc "~/../game.yml"

conditions:
  - "nearest-enemy-distance-norm"
  - "path-length-norm"
  - "enemies-ratio"

sizes:
  - !tup [3, 4]
  - !tup [3, 6]
  - !tup [5, 4]
  - !tup [5, 6]
  - !tup [5, 11]
  - !tup [7, 6]
  - !tup [7, 11]

dataset_config: !obj:methods.ms_gflownet.dataset/Dataset.Config
  data_augmentation: false
  diversity_sampling: true
  diversity_reward: true
  property_reward: "math.log(item['path-length'])"
  cluster_key: &key "(item['nearest-enemy-distance']//(sum(size)//2), item['path-length']//(sum(size)//2))"
  cluster_threshold:
    !tup [3, 4]: 2
    !tup [3, 6]: 2
    !tup [5, 4]: 2
    !tup [5, 6]: 2
    !tup [5,11]: 2
    !tup [7, 6]: 2
    !tup [7,11]: 2

condition_model_config: !obj:methods.ms_conditions/KDEConditionModel.Config
  noise_factors:
    nearest-enemy-distance-norm: !tup [-2, 5]
    path-length-norm: !tup [-5, 10]
    enemies-ratio: !tup [-1, 2]
  diversity_sampling: true
  cluster_key: *key
  cluster_threshold:
    !tup [3, 4]: 2
    !tup [3, 6]: 2
    !tup [5, 4]: 2
    !tup [5, 6]: 2
    !tup [5,11]: 2
    !tup [7, 6]: 2
    !tup [7,11]: 2

generator_config: !inc "configs/models/snake_ms_ce_gru.yml"

optimizer_config: !obj:methods.ms_gflownet.optimizers/GFlowMSTBOptimizer.Config {}

training_steps: 10000
batch_size: 32
checkpoint_period: 1000

heatmap_config: !inc "~/..//heatmap.yml"
heatmap_render_period: 100