!obj:methods.ms_seqgen.trainer/Trainer.Config
game_config: !inc "~/../game.yml"

conditions:
  - "pushed-crate-ratio"
  - "difficulty"

sizes:
  - !tup [3, 3]
  - !tup [4, 4]
  - !tup [5, 5]
  - !tup [6, 6]
  - !tup [7, 7]

dataset_seed_path: "./datasets/sokoban/all_3x3.txt"
dataset_postprocessing: []

dataset_config: !obj:methods.ms_seqgen.dataset/Dataset.Config
  data_augmentation: true
  diversity_sampling: true
  cluster_key: &key "tuple(item['push-signature'])"
  cluster_threshold:
    !tup [3, 3]: 1
    !tup [4, 4]: 1
    !tup [5, 5]: 1
    !tup [6, 6]: 2
    !tup [7, 7]: 2

condition_model_config: !obj:methods.ms_conditions/KDEConditionModel.Config
  noise_factors:
    pushed-crate-ratio: !tup [-1, 1]
    difficulty: !tup [-5, 10]
  diversity_sampling: true
  cluster_key: *key
  cluster_threshold:
    !tup [3, 3]: 1
    !tup [4, 4]: 1
    !tup [5, 5]: 1
    !tup [6, 6]: 2
    !tup [7, 7]: 2

generator_config: !obj:methods.ms_seqgen.models/SnakeMSCEGen.Config
  cell_type: "GRU"
  layer_count: 2
  layer_size: 128
  embedding_size: 32

optimizer_config: !obj:methods.ms_seqgen.optimizers/SeqMSOptimizer.Config {}

training_steps: 10000
batch_size: 32
bootstrapping_period: 1
bootstrapping_batch_size: 32
checkpoint_period: 1000

heatmap_config: !inc "~/..//heatmap.yml"
heatmap_render_period: 100
name_suffix: "PUSHSIG"