controlled_conditions:
  waits:
    tolerence:
      !tup [3, 4]: 2
      !tup [3, 6]: 2
      !tup [5, 4]: 2
      !tup [5, 6]: 2
      !tup [5,11]: 2
      !tup [7, 6]: 2
      !tup [7,11]: 2
      !tup [8,12]: 2
      !tup [9,13]: 2
  solution-length:
    tolerence:
      !tup [3, 4]: 5
      !tup [3, 6]: 5
      !tup [5, 4]: 5
      !tup [5, 6]: 5
      !tup [5,11]: 5
      !tup [7, 6]: 5
      !tup [7,11]: 5
      !tup [8,12]: 5
      !tup [9,13]: 5