!obj:common.heatmap/Heatmaps.Config
labels: ["Pushed Crates", "Solution Length"]
coordinates: ["item['pushed-crates']", "item['solution-length']"]
bounds:
  !tup [3, 3]: !tup [!tup [1, 9],  !tup [1, 27]]
  !tup [4, 4]: !tup [!tup [1, 16], !tup [1, 48]]
  !tup [5, 5]: !tup [!tup [1, 25], !tup [1, 75]]
  !tup [6, 6]: !tup [!tup [1, 36], !tup [1,108]]
  !tup [7, 7]: !tup [!tup [1, 49], !tup [1,147]]