!obj:methods.ms_gflownet.trainer/Trainer.Config
game_config: !obj:games/GameConfig
  name: sokoban
  options:
    solver_iteration_limits:
      !tup [3, 3]: 5.0e+2
      !tup [4, 4]: 5.0e+4
      !tup [5, 5]: 5.0e+5
      !tup [6, 6]: 1.0e+6
      !tup [7, 7]: 1.0e+6

conditions:
  - "pushed-crate-ratio"
  - "difficulty"

sizes:
  - !tup [3, 3]
  - !tup [4, 4]
  - !tup [5, 5]
  - !tup [6, 6]
  - !tup [7, 7]

dataset_config: !obj:methods.ms_gflownet.dataset/Dataset.Config
  data_augmentation: true
  diversity_sampling: true
  diversity_reward: true
  property_reward: "math.log(item['solution-length'])"
  cluster_key: "(item['pushed-crates'], item['solution-length']//10)"
  cluster_threshold:
    !tup [3, 3]: 1
    !tup [4, 4]: 1
    !tup [5, 5]: 1
    !tup [6, 6]: 2
    !tup [7, 7]: 2

condition_model_config: !obj:methods.ms_conditions/KDEConditionModel.Config
  noise_factors:
    pushed-crate-ratio: !tup [-2, 4]
    difficulty: !tup [-10, 20]
  fallback_tree: {}
  diversity_sampling: true
  cluster_key: "(item['pushed-crates'], item['solution-length']//10)"
  cluster_threshold:
    !tup [3, 3]: 1
    !tup [4, 4]: 1
    !tup [5, 5]: 1
    !tup [6, 6]: 2
    !tup [7, 7]: 2

generator_config: !inc "configs/models/snake_ms_ce_lstm.yml"

optimizer_config: !obj:methods.ms_gflownet.optimizers/GFlowMSTBOptimizer.Config {}

training_steps: 10000
batch_size: 32
checkpoint_period: 1000

heatmap_config: !inc "configs/sokoban/heatmap.yml"
heatmap_render_period: 100