controlled_conditions:
  walls:
    tolerence:
      !tup [4, 4]: 4
      !tup [4, 8]: 6
      !tup [8, 4]: 6
      !tup [8, 8]: 8
      !tup [14, 8]: 10
      !tup [8, 14]: 10
      !tup [14, 14]: 14
      !tup [20, 14]: 17
      !tup [20, 20]: 20
  path-length:
    tolerence:
      !tup [4, 4]: 4
      !tup [4, 8]: 6
      !tup [8, 4]: 6
      !tup [8, 8]: 8
      !tup [14, 8]: 10
      !tup [8, 14]: 10
      !tup [14, 14]: 14
      !tup [20, 14]: 17
      !tup [20, 20]: 20